import { sqliteTable, text, integer, real, index, uniqueIndex } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  login: text("login").notNull().unique(),
  password: text("password").notNull(),
  fullName: text("full_name").notNull(),
  roleName: text("role_name").notNull(),
  status: text("status").notNull().default("A"),
});

export const companyProfile = sqliteTable("company_profile", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  address: text("address"),
  city: text("city"),
  phone: text("phone"),
  email: text("email"),
  ntn: text("ntn"),
  gstNo: text("gst_no"),
  logoDataUrl: text("logo_data_url"),
  currentFy: text("current_fy").notNull(),
  fyStart: text("fy_start").notNull(),
  fyEnd: text("fy_end").notNull(),
});

export const postingAccounts = sqliteTable("posting_accounts", {
  key: text("key").primaryKey(),
  accCode: text("acc_code").notNull(),
  label: text("label").notNull(),
  vtype: text("vtype"),
  updatedAt: text("updated_at"),
});

export const fiscalYears = sqliteTable("fiscal_years", {
  code: text("code").primaryKey(),
  description: text("description").notNull(),
  startDate: text("start_date").notNull(),
  endDate: text("end_date").notNull(),
  status: text("status").notNull().default("A"),
});

export const chartOfAccounts = sqliteTable("chart_of_accounts", {
  code: text("code").primaryKey(),
  codeHead: text("code_head").notNull(),
  codeAuto: text("code_auto").notNull().default("0"),
  level: integer("level").notNull(),
  description: text("description").notNull(),
  descShort: text("desc_short"),
  address: text("address"),
  city: text("city"),
  phone: text("phone"),
  mobile: text("mobile"),
  fax: text("fax"),
  email: text("email"),
  gstNo: text("gst_no"),
  ntn: text("ntn"),
  nic: text("nic"),
  creditLimit: real("credit_limit"),
  remarks: text("remarks"),
  contactPerson1: text("contact_person_1"),
  contactDesig1: text("contact_desig_1"),
  contactNo1: text("contact_no_1"),
  contactPerson2: text("contact_person_2"),
  contactDesig2: text("contact_desig_2"),
  contactNo2: text("contact_no_2"),
  contactPerson3: text("contact_person_3"),
  contactDesig3: text("contact_desig_3"),
  contactNo3: text("contact_no_3"),
  bsCode: integer("bs_code"),
  plCode: integer("pl_code"),
  status: text("status").notNull().default("R"),
});

export const costCenters = sqliteTable("cost_centers", {
  code: integer("code").primaryKey(),
  description: text("description").notNull(),
  level: integer("level").notNull().default(1),
  parentCode: integer("parent_code"),
});

export const voucherTypes = sqliteTable("voucher_types", {
  vtype: text("vtype").primaryKey(),
  description: text("description").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
});

export const transMain = sqliteTable("trans_main", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  fyCode: text("fy_code").notNull(),
  vtype: text("vtype").notNull(),
  vno: integer("vno").notNull(),
  vdate: text("vdate").notNull(),
  vdateModified: text("vdate_modified"),
  accCode: text("acc_code"),
  term: text("term"),
  utCode: integer("ut_code"),
  narration: text("narration"),
  vtime: text("vtime"),
  dueDate: text("due_date"),
  expDate: text("exp_date"),
  trnType: text("trn_type"),
  img: text("img"),
  splitting: text("splitting"),
  balanceAmount: real("balance_amount"),
}, (t) => ({
  uxFyVtypeVno: uniqueIndex("ux_trans_main_fy_vtype_vno").on(t.fyCode, t.vtype, t.vno),
}));

export const transDetail = sqliteTable("trans_detail", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  fyCode: text("fy_code").notNull(),
  vtype: text("vtype").notNull(),
  vno: integer("vno").notNull(),
  srno: integer("srno").notNull(),
  accCode: text("acc_code").notNull(),
  partyCode: text("party_code"),
  ccCode: integer("cc_code"),
  narration: text("narration"),
  debit: real("debit").notNull().default(0),
  credit: real("credit").notNull().default(0),
  chqNo: text("chq_no"),
  chqDate: text("chq_date"),
  yarnCount: text("yarn_count"),
  contNo: text("cont_no"),
  statusOk: text("status_ok"),
}, (t) => ({
  uxFyVtypeVnoSrno: uniqueIndex("ux_trans_detail_fy_vtype_vno_srno").on(t.fyCode, t.vtype, t.vno, t.srno),
  ixAccCode: index("ix_trans_detail_acc").on(t.accCode),
}));

export const yarnCounts = sqliteTable("yarn_counts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  countCode: text("count_code").notNull().unique(),
  description: text("description").notNull(),
  ply: integer("ply").notNull().default(1),
  type: text("type").notNull().default("COTTON"),
  denier: real("denier"),
  status: text("status").notNull().default("A"),
});

export const looms = sqliteTable("looms", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  loomNo: integer("loom_no").notNull(),
  shed: text("shed").notNull(),
  type: text("type").notNull(),
  make: text("make"),
  width: real("width"),
  rpm: integer("rpm"),
  actRpm: integer("act_rpm"),
  weaverName: text("weaver_name"),
  group: text("group"),
  forman: text("forman"),
  status: text("status").notNull().default("A"),
  statusWrk: text("status_wrk"),
  currentContract: text("current_contract"),
  currentProduct: text("current_product"),
  currentBeam: text("current_beam"),
}, (t) => ({
  uxShedLoom: uniqueIndex("ux_looms_shed_loom_no").on(t.shed, t.loomNo),
}));

export const greyConstruction = sqliteTable("grey_construction", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: text("code").notNull().unique(),
  description: text("description").notNull(),
  reed: real("reed"),
  pick: real("pick"),
  width: real("width"),
  warpCount: text("warp_count"),
  warp2: text("warp_2"),
  warp3: text("warp_3"),
  warp4: text("warp_4"),
  warp5: text("warp_5"),
  warp6: text("warp_6"),
  warp7: text("warp_7"),
  warp8: text("warp_8"),
  weftCount: text("weft_count"),
  weft2: text("weft_2"),
  weft3: text("weft_3"),
  weft4: text("weft_4"),
  weft5: text("weft_5"),
  weft6: text("weft_6"),
  weft7: text("weft_7"),
  weft8: text("weft_8"),
  weaveType: text("weave_type").notNull().default("PLAIN"),
  selvage: text("selvage"),
  blend: text("blend"),
  gsm: real("gsm"),
  status: text("status").notNull().default("A"),
});

export const contracts = sqliteTable("contracts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractNo: text("contract_no").notNull(),
  fyCode: text("fy_code").notNull(),
  type: text("type").notNull(),
  party: text("party").notNull(),
  broker: text("broker"),
  product: text("product"),
  quantity: real("quantity"),
  rate: real("rate"),
  amount: real("amount"),
  unit: text("unit"),
  contractDate: text("contract_date"),
  deliveryDate: text("delivery_date"),
  status: text("status").notNull().default("A"),
  remarks: text("remarks"),
}, (t) => ({
  uxContractNoFy: uniqueIndex("ux_contracts_no_fy").on(t.contractNo, t.fyCode),
  ixType: index("ix_contracts_type").on(t.type),
}));

export const dailyProduction = sqliteTable("daily_production", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  productionDate: text("production_date").notNull(),
  shed: text("shed").notNull(),
  shift: text("shift").notNull(),
  loomNo: integer("loom_no").notNull(),
  contractNo: text("contract_no"),
  greyCode: text("grey_code"),
  meters: real("meters").notNull().default(0),
  picks: real("picks").notNull().default(0),
  gradeA: real("grade_a").notNull().default(0),
  gradeB: real("grade_b").notNull().default(0),
  gradeC: real("grade_c").notNull().default(0),
  rejection: real("rejection").notNull().default(0),
  rpm: integer("rpm"),
  efficiency: real("efficiency"),
  weaverName: text("weaver_name"),
  foldingStock: real("folding_stock"),
  setNo: text("set_no"),
  looms: integer("looms"),
  grade: text("grade"),
  remarks: text("remarks"),
  lvNo: integer("lv_no"),
  mmThanSrNo: text("mm_than_sr_no"),
  aCount: real("a_count"),
  bCount: real("b_count"),
  cCount: real("c_count"),
  ppc: real("ppc"),
  totalCount: real("total_count"),
  rej: real("rej"),
  beamSetNo: text("beam_set_no"),
  wastWtKg: real("wast_wt_kg"),
  beamNo: text("beam_no"),
  ends: integer("ends"),
  bLength: real("b_length"),
  rcvdMtr: real("rcvd_mtr"),
  diff: real("diff"),
  shrinkage: real("shrinkage"),
  prodDiff: real("prod_diff"),
  productQuality: text("product_quality"),
  productBrand: text("product_brand"),
  salvage: text("salvage"),
  convContParty: text("conv_cont_party"),
  beamContParty: text("beam_cont_party"),
  szgParty: text("szg_party"),
  shiftIncharge: text("shift_incharge"),
  tm: real("tm"),
  pm: real("pm"),
  aShift: real("a_shift"),
  bShift: real("b_shift"),
  cShift: real("c_shift"),
  shift1: real("shift_1"),
  shift2: real("shift_2"),
  shift3: real("shift_3"),
  noOfWidths: integer("no_of_widths"),
  prdCode: text("prd_code"),
  lotNo: text("lot_no"),
  torOwn: text("tor_own"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  uxDateShedShiftLoom: uniqueIndex("ux_daily_prod_date_shed_shift_loom").on(t.productionDate, t.shed, t.shift, t.loomNo),
  ixDate: index("ix_daily_prod_date").on(t.productionDate),
  ixLoom: index("ix_daily_prod_loom").on(t.loomNo),
}));

export const chartParts = sqliteTable("chart_parts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: text("code").notNull().unique(),
  description: text("description").notNull(),
  category: text("category"),
  unit: text("unit").notNull().default("PCS"),
  minStock: real("min_stock").notNull().default(0),
  currentStock: real("current_stock").notNull().default(0),
  avgCost: real("avg_cost").notNull().default(0),
  lastPurchaseDate: text("last_purchase_date"),
  location: text("location"),
  status: text("status").notNull().default("A"),
});

export const beams = sqliteTable("beams", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  beamNo: text("beam_no").notNull().unique(),
  type: text("type").notNull(),
  partyTrade: text("party_trade"),
  codeConv: text("code_conv"),
  statusLoc: text("status_loc"),
  szgParty: text("szg_party"),
  contractNo: text("contract_no"),
  product: text("product"),
  yarnCount: text("yarn_count"),
  ends: integer("ends"),
  length: real("length"),
  weight: real("weight"),
  shed: text("shed"),
  loomNo: integer("loom_no"),
  setNo: text("set_no"),
  beamSetNo: text("beam_set_no"),
  setStatus: text("set_status"),
  brVno: text("br_vno"),
  brDate: text("br_date"),
  knVno: text("kn_vno"),
  knDate: text("kn_date"),
  statusWrk: text("status_wrk").notNull().default("EMPTY"),
  receivedDate: text("received_date"),
});

export const systemLocking = sqliteTable("system_locking", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  module: text("module").notNull().unique(),
  description: text("description").notNull(),
  lockDate: text("lock_date"),
  lockedBy: text("locked_by"),
});

export const endOfDayImages = sqliteTable("end_of_day_images", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  imgDate: text("img_date").notNull(),
  category: text("category"),
  img: text("img").notNull(),
  remarks: text("remarks"),
  uploadedBy: integer("uploaded_by"),
  createdAt: text("created_at").notNull(),
}, (t) => ({
  ixDate: index("ix_eod_img_date").on(t.imgDate),
}));

export const storeAdjustments = sqliteTable("store_adjustments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  adjNo: integer("adj_no").notNull(),
  fyCode: text("fy_code").notNull(),
  adjDate: text("adj_date").notNull(),
  type: text("type").notNull().default("ADJ"),
  remarks: text("remarks"),
  itemCount: integer("item_count"),
  totalValue: real("total_value"),
  approvalStatus: text("approval_status").notNull().default("STORE"),
  auditedBy: integer("audited_by"),
  auditedAt: text("audited_at"),
  postedBy: integer("posted_by"),
  postedAt: text("posted_at"),
}, (t) => ({
  uxFyAdj: uniqueIndex("ux_store_adj_fy_no").on(t.fyCode, t.adjNo),
}));

export const storeAdjustmentDetail = sqliteTable("store_adjustment_detail", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  adjId: integer("adj_id").notNull().references(() => storeAdjustments.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  partCode: text("part_code").notNull(),
  qty: real("qty").notNull(),
  rate: real("rate").notNull(),
  amount: real("amount").notNull(),
  reason: text("reason"),
}, (t) => ({
  ixAdj: index("ix_store_adj_detail_adj").on(t.adjId),
  ixPart: index("ix_store_adj_detail_part").on(t.partCode),
}));

export const periodLocks = sqliteTable("period_locks", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  fyCode: text("fy_code").notNull(),
  module: text("module").notNull(),
  lockedThrough: text("locked_through").notNull(),
  lockedBy: integer("locked_by"),
  lockedAt: text("locked_at").notNull(),
  remarks: text("remarks"),
}, (t) => ({
  uxFyModule: uniqueIndex("ux_period_locks_fy_module").on(t.fyCode, t.module),
}));

export const cities = sqliteTable("cities", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull().unique(),
});

export const companyUnits = sqliteTable("company_units", {
  code: text("code").primaryKey(),
  srno: integer("srno"),
  description: text("description").notNull(),
});

export const beamStatuses = sqliteTable("beam_statuses", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  status: text("status").notNull().unique(),
});

export const weavers = sqliteTable("weavers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: integer("code").notNull().unique(),
  name: text("name").notNull(),
  nameShort: text("name_short"),
  address: text("address"),
  cell: text("cell"),
  phone: text("phone"),
});

export const yarnBlends = sqliteTable("yarn_blends", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  description: text("description").notNull().unique(),
});

export const yarnBrands = sqliteTable("yarn_brands", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull().unique(),
});

export const yarnFibers = sqliteTable("yarn_fibers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: integer("code").notNull().unique(),
  type: text("type"),
  description: text("description").notNull(),
  denier: text("denier"),
  length: text("length"),
});

export const greyDspChart = sqliteTable("grey_dsp_chart", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: integer("code").notNull().unique(),
  name: text("name").notNull(),
  nameShort: text("name_short"),
  cell: text("cell"),
  phone: text("phone"),
});

export const doPartyChart = sqliteTable("do_party_chart", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: integer("code").notNull().unique(),
  name: text("name").notNull(),
  nameShort: text("name_short"),
  cell: text("cell"),
  phone: text("phone"),
});

export const locations = sqliteTable("locations", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: integer("code").notNull(),
  description: text("description").notNull(),
  type: text("type").notNull().default("GREY"),
}, (t) => ({
  uxCodeType: uniqueIndex("ux_locations_code_type").on(t.code, t.type),
}));

export const productionStaff = sqliteTable("production_staff", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: integer("code").notNull().unique(),
  level: integer("level").notNull().default(1),
  name: text("name").notNull(),
  nameShort: text("name_short"),
  cell: text("cell"),
  phone: text("phone"),
  shed: integer("shed"),
  shift: text("shift"),
  status: text("status").notNull().default("A"),
});

export const partyCounts = sqliteTable("party_counts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  partyCode: text("party_code").notNull(),
  countCode: integer("count_code").notNull(),
  ratePerLbs: real("rate_per_lbs"),
  calCountWeft: real("cal_count_weft"),
  calCountWarp: real("cal_count_warp"),
  status: text("status"),
  trnType: text("trn_type"),
  countGroup: text("count_group"),
}, (t) => ({
  uxPartyCount: uniqueIndex("ux_party_counts_party_count").on(t.partyCode, t.countCode),
}));

export const products = sqliteTable("products", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: integer("code").notNull().unique(),
  description: text("description").notNull(),
  mainDesc: text("main_desc"),
  subDesc: text("sub_desc"),
  mainCode: integer("main_code"),
  subCode: integer("sub_code"),
});

export const productsMain = sqliteTable("products_main", {
  code: integer("code").primaryKey(),
  description: text("description").notNull(),
});

export const productsSub = sqliteTable("products_sub", {
  code: integer("code").primaryKey(),
  description: text("description").notNull(),
});

export const chartDefine = sqliteTable("chart_define", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: integer("code").notNull().unique(),
  description: text("description").notNull(),
  srno: integer("srno"),
});

export const yarnTransactions = sqliteTable("yarn_transactions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  transType: text("trans_type").notNull(),
  transDate: text("trans_date").notNull(),
  transNo: integer("trans_no").notNull(),
  fyCode: text("fy_code").notNull(),
  party: text("party"),
  yarnCount: text("yarn_count"),
  bags: integer("bags"),
  weightKg: real("weight_kg"),
  rate: real("rate"),
  amount: real("amount"),
  vehicleNo: text("vehicle_no"),
  biltyNo: text("bilty_no"),
  fromLocation: text("from_location"),
  toLocation: text("to_location"),
  remarks: text("remarks"),
  status: text("status").notNull().default("A"),
});

export const beamTransactions = sqliteTable("beam_transactions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  transType: text("trans_type").notNull(),
  transDate: text("trans_date").notNull(),
  transNo: integer("trans_no").notNull(),
  fyCode: text("fy_code").notNull(),
  beamNo: text("beam_no"),
  party: text("party"),
  yarnCount: text("yarn_count"),
  ends: integer("ends"),
  length: real("length"),
  weight: real("weight"),
  fromLocation: text("from_location"),
  toLocation: text("to_location"),
  status: text("status").notNull().default("A"),
});

export const knottingTransactions = sqliteTable("knotting_transactions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  transDate: text("trans_date").notNull(),
  transNo: integer("trans_no").notNull(),
  fyCode: text("fy_code").notNull(),
  contractNo: text("contract_no"),
  beamNo: text("beam_no"),
  transType: text("trans_type").notNull(),
  weaver: text("weaver"),
  loomNo: integer("loom_no"),
  rate: real("rate"),
  amount: real("amount"),
  status: text("status").notNull().default("A"),
});

export const productionHours = sqliteTable("production_hours", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  scheduleDate: text("schedule_date").notNull(),
  shed: text("shed").notNull(),
  shift: text("shift").notNull(),
  startTime: text("start_time").notNull(),
  endTime: text("end_time").notNull(),
  hours: real("hours").notNull(),
  loomsRunning: integer("looms_running"),
  remarks: text("remarks"),
});

export const greyDespatch = sqliteTable("grey_despatch", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  despatchNo: integer("despatch_no").notNull(),
  fyCode: text("fy_code").notNull(),
  despatchDate: text("despatch_date").notNull(),
  party: text("party").notNull(),
  partyCode: integer("party_code"),
  product: text("product"),
  meters: real("meters"),
  rolls: integer("rolls"),
  vehicleNo: text("vehicle_no"),
  biltyNo: text("bilty_no"),
  gatePassNo: text("gate_pass_no"),
  status: text("status").notNull().default("A"),
});

export const storeDemands = sqliteTable("store_demands", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  demandNo: integer("demand_no").notNull(),
  fyCode: text("fy_code").notNull(),
  demandDate: text("demand_date").notNull(),
  department: text("department").notNull(),
  requestedBy: text("requested_by"),
  itemCount: integer("item_count"),
  totalAmount: real("total_amount"),
  status: text("status").notNull().default("P"),
  remarks: text("remarks"),
  approvalStatus: text("approval_status").notNull().default("STORE"),
  auditedBy: integer("audited_by"),
  auditedAt: text("audited_at"),
  postedBy: integer("posted_by"),
  postedAt: text("posted_at"),
});

export const storeGrn = sqliteTable("store_grn", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  grnNo: integer("grn_no").notNull(),
  fyCode: text("fy_code").notNull(),
  grnDate: text("grn_date").notNull(),
  supplier: text("supplier").notNull(),
  supplierCode: text("supplier_code"),
  invoiceNo: text("invoice_no"),
  itemCount: integer("item_count"),
  totalAmount: real("total_amount"),
  status: text("status").notNull().default("A"),
  approvalStatus: text("approval_status").notNull().default("STORE"),
  auditedBy: integer("audited_by"),
  auditedAt: text("audited_at"),
  postedBy: integer("posted_by"),
  postedAt: text("posted_at"),
});

export const storeGrnDetail = sqliteTable("store_grn_detail", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  grnId: integer("grn_id").notNull().references(() => storeGrn.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  partCode: text("part_code").notNull(),
  qty: real("qty").notNull(),
  rateBill: real("rate_bill"),
  discPer: real("disc_per"),
  taxPer: real("tax_per"),
  rate: real("rate").notNull(),
  amount: real("amount").notNull(),
}, (t) => ({
  ixGrn: index("ix_store_grn_detail_grn").on(t.grnId),
  ixPart: index("ix_store_grn_detail_part").on(t.partCode),
}));

export const storeDemandDetail = sqliteTable("store_demand_detail", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  demandId: integer("demand_id").notNull().references(() => storeDemands.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  partCode: text("part_code").notNull(),
  qty: real("qty").notNull(),
  rate: real("rate").notNull(),
  amount: real("amount").notNull(),
  ccCode: text("cc_code"),
}, (t) => ({
  ixDemand: index("ix_store_demand_detail_demand").on(t.demandId),
  ixPart: index("ix_store_demand_detail_part").on(t.partCode),
}));

export const storeReturns = sqliteTable("store_returns", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  returnNo: integer("return_no").notNull(),
  fyCode: text("fy_code").notNull(),
  returnDate: text("return_date").notNull(),
  department: text("department").notNull(),
  returnedBy: text("returned_by"),
  itemCount: integer("item_count"),
  totalAmount: real("total_amount"),
  remarks: text("remarks"),
  approvalStatus: text("approval_status").notNull().default("STORE"),
  auditedBy: integer("audited_by"),
  auditedAt: text("audited_at"),
  postedBy: integer("posted_by"),
  postedAt: text("posted_at"),
}, (t) => ({
  uxFyNo: uniqueIndex("ux_store_returns_fy_no").on(t.fyCode, t.returnNo),
}));

export const storeReturnDetail = sqliteTable("store_return_detail", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  returnId: integer("return_id").notNull().references(() => storeReturns.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  partCode: text("part_code").notNull(),
  qty: real("qty").notNull(),
  rate: real("rate").notNull(),
  amount: real("amount").notNull(),
}, (t) => ({
  ixReturn: index("ix_store_return_detail_return").on(t.returnId),
  ixPart: index("ix_store_return_detail_part").on(t.partCode),
}));

export const storeGatepass = sqliteTable("store_gatepass", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  gatepassNo: integer("gatepass_no").notNull(),
  fyCode: text("fy_code").notNull(),
  gatepassDate: text("gatepass_date").notNull(),
  gatepassType: text("gatepass_type").notNull(),
  party: text("party").notNull(),
  vehicleNo: text("vehicle_no"),
  purpose: text("purpose"),
  itemCount: integer("item_count"),
  status: text("status").notNull().default("A"),
});

export const inventoryOpening = sqliteTable("inventory_opening", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  fyCode: text("fy_code").notNull(),
  itemType: text("item_type").notNull(),
  itemCode: text("item_code").notNull(),
  description: text("description").notNull(),
  openingQty: real("opening_qty").notNull().default(0),
  openingRate: real("opening_rate").notNull().default(0),
  openingAmount: real("opening_amount").notNull().default(0),
  unit: text("unit").notNull().default("KG"),
  location: text("location"),
  entryDate: text("entry_date"),
  status: text("status").notNull().default("A"),
  voucherNo: text("voucher_no"),
  doDate: text("do_date"),
  purContNo: text("pur_cont_no"),
  opnParty: text("opn_party"),
  convContNo: text("conv_cont_no"),
  ratio: text("ratio"),
  qtyWarp: real("qty_warp"),
  qtyWeft: real("qty_weft"),
  qtyBags: real("qty_bags"),
  brand: text("brand"),
  remarks: text("remarks"),
  grayWidth: real("gray_width"),
  weave: text("weave"),
  designNo: text("design_no"),
  loomType: text("loom_type"),
  lvNo: text("lv_no"),
  grayConstruction: text("gray_construction"),
  productName: text("product_name"),
  blend: text("blend"),
  than: real("than"),
  rejection: real("rejection"),
  netMtr: real("net_mtr"),
  setNo: text("set_no"),
  beamSetNo: text("beam_set_no"),
  beamNo: text("beam_no"),
  wrpCont: text("wrp_cont"),
  warpSizingParty: text("warp_sizing_party"),
  convParty: text("conv_party"),
}, (t) => ({
  ixItemType: index("ix_inv_opening_item_type").on(t.itemType),
  ixFyCode: index("ix_inv_opening_fy_code").on(t.fyCode),
  ixEntryDate: index("ix_inv_opening_entry_date").on(t.entryDate),
}));

export const branchOpening = sqliteTable("branch_opening", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  branchCode: text("branch_code").notNull().unique(),
  branchName: text("branch_name").notNull(),
  address: text("address"),
  city: text("city"),
  phone: text("phone"),
  fyCode: text("fy_code").notNull(),
  openingDate: text("opening_date").notNull(),
  status: text("status").notNull().default("A"),
});

export const tickets = sqliteTable("tickets", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  ticketNo: text("ticket_no").notNull().unique(),
  title: text("title").notNull(),
  description: text("description"),
  type: text("type").notNull(),
  priority: text("priority").notNull().default("P3_NORMAL"),
  status: text("status").notNull().default("OPEN"),
  assigneeUserId: integer("assignee_user_id").references(() => users.id, { onDelete: "set null" }),
  reporterUserId: integer("reporter_user_id").notNull().references(() => users.id),
  shed: text("shed"),
  loomNo: integer("loom_no"),
  contractNo: text("contract_no"),
  partyCode: text("party_code"),
  greyCode: text("grey_code"),
  beamNo: text("beam_no"),
  labels: text("labels"),
  dueDate: text("due_date"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  resolvedAt: text("resolved_at"),
}, (t) => ({
  ixStatus: index("ix_tickets_status").on(t.status),
  ixAssignee: index("ix_tickets_assignee").on(t.assigneeUserId),
  ixReporter: index("ix_tickets_reporter").on(t.reporterUserId),
  ixLoom: index("ix_tickets_loom").on(t.loomNo),
  ixType: index("ix_tickets_type").on(t.type),
  ixPriority: index("ix_tickets_priority").on(t.priority),
}));

export const ticketComments = sqliteTable("ticket_comments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  ticketId: integer("ticket_id").notNull().references(() => tickets.id, { onDelete: "cascade" }),
  authorUserId: integer("author_user_id").notNull().references(() => users.id),
  body: text("body").notNull(),
  createdAt: text("created_at").notNull(),
}, (t) => ({
  ixTicket: index("ix_ticket_comments_ticket").on(t.ticketId),
}));

export const ticketHistory = sqliteTable("ticket_history", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  ticketId: integer("ticket_id").notNull().references(() => tickets.id, { onDelete: "cascade" }),
  actorUserId: integer("actor_user_id").notNull().references(() => users.id),
  action: text("action").notNull(),
  fromValue: text("from_value"),
  toValue: text("to_value"),
  createdAt: text("created_at").notNull(),
}, (t) => ({
  ixTicket: index("ix_ticket_history_ticket").on(t.ticketId),
}));

export const greyPakiParchi = sqliteTable("grey_paki_parchi", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  ppNo: integer("pp_no").notNull(),
  fyCode: text("fy_code").notNull(),
  ppDate: text("pp_date").notNull(),
  party: text("party").notNull(),
  partyCode: text("party_code"),
  greyCode: integer("grey_code"),
  loomType: text("loom_type"),
  qtyThan: integer("qty_than"),
  qtyMtrs: real("qty_mtrs"),
  qtyMtrsNet: real("qty_mtrs_net"),
  greyPick: integer("grey_pick"),
  greyWidth: real("grey_width"),
  rate: real("rate"),
  amount: real("amount"),
  contractNo: text("contract_no"),
  remarks: text("remarks"),
  status: text("status").notNull().default("A"),
});

// ============================================================
// INVENTORY EXTERNAL — Contracts, Yarn/Grey Transactions, Reports
// Mirrors Oracle Forms 6i modules exactly. All ext_* tables.
// ============================================================

// --- CONTRACTS ---

export const extYarnPurContract = sqliteTable("ext_yarn_pur_contract", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contNo: text("cont_no").notNull().unique(),
  lContNo: integer("l_cont_no"),
  contDate: text("cont_date").notNull(),
  expdDate: text("expd_date"),
  refno: text("refno"),
  partyCode: text("party_code"),
  broker: text("broker"),
  agePercent: real("age_percent"),
  brokagePerBag: real("brokage_per_bag"),
  countCode: text("count_code"),
  ratio: text("ratio"),
  brand: text("brand"),
  qtyBags: real("qty_bags"),
  qtyLbs: real("qty_lbs"),
  ratePerLbs: real("rate_per_lbs"),
  amount: real("amount"),
  days: integer("days"),
  remarks: text("remarks"),
  img: text("img"),
  status: text("status").notNull().default("R"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_ext_ypc_party").on(t.partyCode),
  ixStatus: index("ix_ext_ypc_status").on(t.status),
}));

export const extYarnPurContractDelivery = sqliteTable("ext_yarn_pur_contract_delivery", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractId: integer("contract_id").notNull().references(() => extYarnPurContract.id, { onDelete: "cascade" }),
  deliveryDate: text("delivery_date"),
  doNo: text("do_no"),
  bags: real("bags"),
  ycdDlvLoc: text("ycd_dlv_loc"),
}, (t) => ({
  ixContract: index("ix_ext_ypcd_contract").on(t.contractId),
}));

export const extYarnSalContract = sqliteTable("ext_yarn_sal_contract", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contNo: text("cont_no").notNull().unique(),
  lContNo: integer("l_cont_no"),
  contDate: text("cont_date").notNull(),
  expdDate: text("expd_date"),
  refno: text("refno"),
  partyCode: text("party_code"),
  broker: text("broker"),
  brokagePercentage: real("brokage_percentage"),
  agePercent: real("age_percent"),
  countCode: text("count_code"),
  ratio: text("ratio"),
  brand: text("brand"),
  qtyBags: real("qty_bags"),
  qtyLbs: real("qty_lbs"),
  ratePerLbs: real("rate_per_lbs"),
  amount: real("amount"),
  days: integer("days"),
  remarks: text("remarks"),
  img: text("img"),
  status: text("status").notNull().default("R"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_ext_ysc_party").on(t.partyCode),
  ixStatus: index("ix_ext_ysc_status").on(t.status),
}));

export const extYarnSalContractDelivery = sqliteTable("ext_yarn_sal_contract_delivery", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractId: integer("contract_id").notNull().references(() => extYarnSalContract.id, { onDelete: "cascade" }),
  deliveryDate: text("delivery_date"),
  bags: real("bags"),
  ycdDlvLoc: text("ycd_dlv_loc"),
}, (t) => ({
  ixContract: index("ix_ext_yscd_contract").on(t.contractId),
}));

export const extGreyPurContract = sqliteTable("ext_grey_pur_contract", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractNo: text("contract_no").notNull().unique(),
  lContNo: integer("l_cont_no"),
  contractDate: text("contract_date").notNull(),
  expDate: text("exp_date"),
  partyRefNo: text("party_ref_no"),
  party: text("party"),
  broker: text("broker"),
  brokagPercentage: real("brokag_percentage"),
  perMtr: real("per_mtr"),
  greyCode: text("grey_code"),
  weave: text("weave"),
  salvage: text("salvage"),
  quantityMtr: real("quantity_mtr"),
  ratePerMtr: real("rate_per_mtr"),
  amount: real("amount"),
  specialInst: text("special_inst"),
  paymentTerm: text("payment_term"),
  deliveryTerm: text("delivery_term"),
  remarks: text("remarks"),
  extMtr: real("ext_mtr"),
  extDate: text("ext_date"),
  gstRate: real("gst_rate"),
  status: text("status").notNull().default("R"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_ext_gpc_party").on(t.party),
  ixStatus: index("ix_ext_gpc_status").on(t.status),
}));

export const extGreyPurContractDelivery = sqliteTable("ext_grey_pur_contract_delivery", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractId: integer("contract_id").notNull().references(() => extGreyPurContract.id, { onDelete: "cascade" }),
  deliveryDate: text("delivery_date"),
  meters: real("meters"),
  location: text("location"),
}, (t) => ({
  ixContract: index("ix_ext_gpcd_contract").on(t.contractId),
}));

export const extGreySalContract = sqliteTable("ext_grey_sal_contract", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractNo: text("contract_no").notNull().unique(),
  lContNo: integer("l_cont_no"),
  contractDate: text("contract_date").notNull(),
  expDate: text("exp_date"),
  partyRefNo: text("party_ref_no"),
  party: text("party"),
  broker: text("broker"),
  brokagPerBag: real("brokag_per_bag"),
  perMtr: real("per_mtr"),
  greyCode: text("grey_code"),
  weave: text("weave"),
  salvage: text("salvage"),
  quantityMtr: real("quantity_mtr"),
  ratePerMtr: real("rate_per_mtr"),
  amount: real("amount"),
  days: integer("days"),
  specialInst: text("special_inst"),
  paymentTerm: text("payment_term"),
  deliveryTerm: text("delivery_term"),
  remarks: text("remarks"),
  extMtr: real("ext_mtr"),
  extDate: text("ext_date"),
  gstRate: real("gst_rate"),
  img: text("img"),
  status: text("status").notNull().default("R"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_ext_gsc_party").on(t.party),
  ixStatus: index("ix_ext_gsc_status").on(t.status),
}));

export const extGreySalContractDelivery = sqliteTable("ext_grey_sal_contract_delivery", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractId: integer("contract_id").notNull().references(() => extGreySalContract.id, { onDelete: "cascade" }),
  deliveryDate: text("delivery_date"),
  meters: real("meters"),
  location: text("location"),
}, (t) => ({
  ixContract: index("ix_ext_gscd_contract").on(t.contractId),
}));

export const extGreyConvContract = sqliteTable("ext_grey_conv_contract", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contNo: text("cont_no").notNull().unique(),
  lContNo: integer("l_cont_no"),
  contDate: text("cont_date").notNull(),
  expDate: text("exp_date"),
  status: text("status").notNull().default("R"),
  type: text("type").notNull().default("CONV"),
  party: text("party"),
  weaveFrame: text("weave_frame"),
  selvType: text("selv_type"),
  slvName: text("slv_name"),
  qtyMtr: real("qty_mtr"),
  costLakhaiBorderMtr: real("cost_lakhai_border_mtr"),
  ratePerPick: real("rate_per_pick"),
  rateMtr: real("rate_mtr"),
  convRatePerMtr: real("conv_rate_per_mtr"),
  grayRatePerMtr: real("gray_rate_per_mtr"),
  loomType: text("loom_type"),
  broker: text("broker"),
  ratePick: real("rate_pick"),
  designNo: text("design_no"),
  grayQltyCode: text("gray_qlty_code"),
  img: text("img"),
  wrpWt40: real("wrp_wt_40"),
  wftWt40: real("wft_wt_40"),
  weight40: real("weight_40"),
  remarks: text("remarks"),
  read: real("read"),
  pick: real("pick"),
  width: real("width"),
  findDesign: text("find_design"),
  grayCode: text("gray_code"),
  findContract: text("find_contract"),
  warpWtPerMtr: real("warp_wt_per_mtr"),
  weftWtPerMtr: real("weft_wt_per_mtr"),
  wtPerMtr: real("wt_per_mtr"),
  warpCostPerMtr: real("warp_cost_per_mtr"),
  weftCostPerMtr: real("weft_cost_per_mtr"),
  costPerMtr: real("cost_per_mtr"),
  ratePerMtr1: real("rate_per_mtr_1"),
  ratePerMtr2: real("rate_per_mtr_2"),
  productName: text("product_name"),
  productQuality: text("product_quality"),
  seasonType: text("season_type"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_ext_gcc_party").on(t.party),
  ixStatus: index("ix_ext_gcc_status").on(t.status),
}));

export const extGreyConvWarp = sqliteTable("ext_grey_conv_warp", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractId: integer("contract_id").notNull().references(() => extGreyConvContract.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  count: text("count"),
  descr: text("descr"),
  brand: text("brand"),
  calCount: real("cal_count"),
  ends: integer("ends"),
  wtPerMtr: real("wt_per_mtr"),
  ratePerLbs: real("rate_per_lbs"),
  costPerMtr: real("cost_per_mtr"),
}, (t) => ({
  ixContract: index("ix_ext_gcw_contract").on(t.contractId),
}));

export const extGreyConvWeft = sqliteTable("ext_grey_conv_weft", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractId: integer("contract_id").notNull().references(() => extGreyConvContract.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  count: text("count"),
  descr: text("descr"),
  brand: text("brand"),
  calCount: real("cal_count"),
  ends: integer("ends"),
  wtPerMtr: real("wt_per_mtr"),
  ratePerLbs: real("rate_per_lbs"),
  costPerMtr: real("cost_per_mtr"),
}, (t) => ({
  ixContract: index("ix_ext_gcwft_contract").on(t.contractId),
}));

// --- YARN TRANSACTIONS (Vouchers with line items) ---

export const extYarnPurVoucher = sqliteTable("ext_yarn_pur_voucher", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vNo: text("v_no").notNull().unique(),
  lvNo: integer("lv_no"),
  vDate: text("v_date").notNull(),
  type: text("type").notNull().default("PUR"),
  posting: text("posting").notNull().default("N"),
  loomType: text("loom_type"),
  bmParty: text("bm_party"),
  party: text("party"),
  broker: text("broker"),
  term: text("term").notNull().default("CASH"),
  dueDate: text("due_date"),
  img: text("img"),
  cont: text("cont"),
  pur: real("pur"),
  bal: real("bal"),
  salAvgRate: real("sal_avg_rate"),
  purAvgRate: real("pur_avg_rate"),
  percent: real("percent"),
  perBag: real("per_bag"),
  rkd: real("rkd"),
  lotNo: text("lot_no"),
  pendingFinance: text("pending_finance"),
  statusOk: text("status_ok"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_ext_ypv_party").on(t.party),
  ixDate: index("ix_ext_ypv_date").on(t.vDate),
}));

export const extYarnPurVoucherLine = sqliteTable("ext_yarn_pur_voucher_line", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  voucherId: integer("voucher_id").notNull().references(() => extYarnPurVoucher.id, { onDelete: "cascade" }),
  contNo: text("cont_no"),
  count: text("count"),
  countDot: text("count_dot"),
  partyCount: text("party_count"),
  bld: text("bld"),
  pack: text("pack"),
  brand: text("brand"),
  doNo: text("do_no"),
  qty: real("qty"),
  bag: real("bag"),
  con: real("con"),
  lbs: real("lbs"),
  unit: text("unit"),
  despatchParty: text("despatch_party"),
  rate: real("rate"),
  rateSv: real("rate_sv"),
}, (t) => ({
  ixVoucher: index("ix_ext_ypvl_voucher").on(t.voucherId),
}));

export const extYarnSalVoucher = sqliteTable("ext_yarn_sal_voucher", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vNo: text("v_no").notNull().unique(),
  lvNo: integer("lv_no"),
  vDate: text("v_date").notNull(),
  type: text("type").notNull().default("SAL"),
  posting: text("posting").notNull().default("N"),
  loomType: text("loom_type"),
  party: text("party"),
  broker: text("broker"),
  term: text("term").notNull().default("CASH"),
  dueDate: text("due_date"),
  img: text("img"),
  cont: text("cont"),
  pur: real("pur"),
  bal: real("bal"),
  stockBag: real("stock_bag"),
  stockCon: real("stock_con"),
  stockLbs: real("stock_lbs"),
  ratePv: real("rate_pv"),
  amtPv: real("amt_pv"),
  pl: real("pl"),
  avgRate: real("avg_rate"),
  remarks: text("remarks"),
  pendingFinance: text("pending_finance"),
  statusOk: text("status_ok"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_ext_ysv_party").on(t.party),
  ixDate: index("ix_ext_ysv_date").on(t.vDate),
}));

export const extYarnSalVoucherLine = sqliteTable("ext_yarn_sal_voucher_line", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  voucherId: integer("voucher_id").notNull().references(() => extYarnSalVoucher.id, { onDelete: "cascade" }),
  contNo: text("cont_no"),
  count: text("count"),
  countDot: text("count_dot"),
  partyCount: text("party_count"),
  bld: text("bld"),
  pack: text("pack"),
  brand: text("brand"),
  doNo: text("do_no"),
  qty: real("qty"),
  bag: real("bag"),
  cons: real("cons"),
  lbs: real("lbs"),
  unit: text("unit"),
  despatchParty: text("despatch_party"),
  rate: real("rate"),
  amt: real("amt"),
  remarks: text("remarks"),
}, (t) => ({
  ixVoucher: index("ix_ext_ysvl_voucher").on(t.voucherId),
}));

// --- GREY TRANSACTIONS ---

export const extGodownStock = sqliteTable("ext_godown_stock", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vNo: text("v_no").notNull().unique(),
  lvNo: integer("lv_no"),
  vDate: text("v_date").notNull(),
  kpNo: text("kp_no"),
  type: text("type").notNull().default("STOCK"),
  purchaseParty: text("purchase_party"),
  gdnParty: text("gdn_party"),
  contNo: text("cont_no"),
  purContNo: text("pur_cont_no"),
  contactQuality: text("contact_quality"),
  dspQuality: text("dsp_quality"),
  than: integer("than"),
  meter: real("meter"),
  elCumiNum: integer("el_cumi_num"),
  elCumiDen: integer("el_cumi_den"),
  kamiMtr: real("kami_mtr"),
  rateConversion: real("rate_conversion"),
  term: text("term"),
  days: integer("days"),
  rateSal: real("rate_sal"),
  salContNo: text("sal_cont_no"),
  greySaleCont: text("grey_sale_cont"),
  kaatPercent: real("kaat_percent"),
  elMeter: real("el_meter"),
  elMeterMode: text("el_meter_mode"),
  netMeter: real("net_meter"),
  checkery: real("checkery"),
  commission: real("commission"),
  total: real("total"),
  balance: real("balance"),
  profitPerMtr: real("profit_per_mtr"),
  profitAmt: real("profit_amt"),
  printingName: text("printing_name"),
  brokerName: text("broker_name"),
  remarks: text("remarks"),
  imgHash: text("img_hash"),
  convGreyType: text("conv_grey_type"),
  rate: real("rate"),
  salAvgRate: real("sal_avg_rate"),
  pendingFinance: text("pending_finance"),
  statusOk: text("status_ok"),
  dueDate: text("due_date"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_ext_gs_party").on(t.purchaseParty),
  ixDate: index("ix_ext_gs_date").on(t.vDate),
}));

export const extGodownStockLine = sqliteTable("ext_godown_stock_line", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  stockId: integer("stock_id").notNull().references(() => extGodownStock.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  than: integer("than"),
  mtr: real("mtr"),
  status: text("status"),
}, (t) => ({
  ixStock: index("ix_ext_gsl_stock").on(t.stockId),
}));

export const extGodownStockCount = sqliteTable("ext_godown_stock_count", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  stockId: integer("stock_id").notNull().references(() => extGodownStock.id, { onDelete: "cascade" }),
  code: text("code"),
  type: text("type"),
  calCount: real("cal_count"),
  ends: integer("ends"),
  ratePerLbs: real("rate_per_lbs"),
  wtPerMtr: real("wt_per_mtr"),
  costPerMtr: real("cost_per_mtr"),
  totLbs: real("tot_lbs"),
}, (t) => ({
  ixStock: index("ix_ext_gsc_stock").on(t.stockId),
}));

export const extGreyTransfer = sqliteTable("ext_grey_transfer", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vNo: text("v_no").notNull().unique(),
  lvNo: integer("lv_no"),
  vDate: text("v_date").notNull(),
  greyType: text("grey_type").notNull().default("FRS"),
  partyFrom: text("party_from"),
  qualityFrom: text("quality_from"),
  than: integer("than"),
  meters: real("meters"),
  stockThan: integer("stock_than"),
  stockMtr: real("stock_mtr"),
  partyTo: text("party_to"),
  qualityTo: text("quality_to"),
  remarks: text("remarks"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixDate: index("ix_ext_gt_date").on(t.vDate),
  ixFrom: index("ix_ext_gt_from").on(t.partyFrom),
  ixTo: index("ix_ext_gt_to").on(t.partyTo),
}));

export const extKachiParchi = sqliteTable("ext_kachi_parchi", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vNo: text("v_no").notNull().unique(),
  lvNo: integer("lv_no"),
  vDate: text("v_date").notNull(),
  kpNo: text("kp_no"),
  type: text("type").notNull().default("STOCK"),
  purchaseParty: text("purchase_party"),
  contNo: text("cont_no"),
  salDate: text("sal_date"),
  saleParty: text("sale_party"),
  dspQuality: text("dsp_quality"),
  qualityPrint: text("quality_print"),
  than: integer("than"),
  meter: real("meter"),
  convRate: real("conv_rate"),
  greyRate: real("grey_rate"),
  stockThan: integer("stock_than"),
  stockMtr: real("stock_mtr"),
  avg: real("avg"),
  ratePur: real("rate_pur"),
  rateSal: real("rate_sal"),
  elCumiNum: integer("el_cumi_num"),
  elCumiDen: integer("el_cumi_den"),
  badCumiNum: integer("bad_cumi_num"),
  badCumiDen: integer("bad_cumi_den"),
  elMeter: real("el_meter"),
  baadMeter: real("baad_meter"),
  totalElBadMtrs: real("total_el_bad_mtrs"),
  printingName: text("printing_name"),
  brokerName: text("broker_name"),
  remarks: text("remarks"),
  term: text("term"),
  dueDate: text("due_date"),
  ppVno: text("pp_vno"),
  imgNo: text("img_no"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_ext_kp_party").on(t.purchaseParty),
  ixDate: index("ix_ext_kp_date").on(t.vDate),
}));

export const extKachiParchiLine = sqliteTable("ext_kachi_parchi_line", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  parchiId: integer("parchi_id").notNull().references(() => extKachiParchi.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  than: integer("than"),
  mtr: real("mtr"),
  gdnLineId: integer("gdn_line_id"),
}, (t) => ({
  ixParchi: index("ix_ext_kpl_parchi").on(t.parchiId),
}));

export const extKachiParchiCount = sqliteTable("ext_kachi_parchi_count", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  parchiId: integer("parchi_id").notNull().references(() => extKachiParchi.id, { onDelete: "cascade" }),
  code: text("code"),
  type: text("type"),
  calCount: real("cal_count"),
  ends: integer("ends"),
  ratePerLbs: real("rate_per_lbs"),
  wtPerMtr: real("wt_per_mtr"),
  costPerMtr: real("cost_per_mtr"),
  totLbs: real("tot_lbs"),
}, (t) => ({
  ixParchi: index("ix_ext_kpc_parchi").on(t.parchiId),
}));

export const extPackiParchi = sqliteTable("ext_packi_parchi", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vNo: text("v_no").notNull().unique(),
  vDate: text("v_date").notNull(),
  purchaseParty: text("purchase_party"),
  kpNo: text("kp_no"),
  kpAll: text("kp_all"),
  ppNo: text("pp_no"),
  ppDate: text("pp_date"),
  quality: text("quality"),
  qualityPrint: text("quality_print"),
  meterRe: real("meter_re"),
  meterKam: real("meter_kam"),
  meterNet: real("meter_net"),
  than: integer("than"),
  kpMeter: real("kp_meter"),
  brokerName: text("broker_name"),
  brokerPercent: real("broker_percent"),
  meterFineNum: integer("meter_fine_num"),
  meterFineDen: integer("meter_fine_den"),
  greyRate: real("grey_rate"),
  wokc: real("wokc"),
  wkcBrk: real("wkc_brk"),
  elCumiNum: integer("el_cumi_num"),
  elCumiDen: integer("el_cumi_den"),
  elMeter: real("el_meter"),
  elMeterMode: text("el_meter_mode"),
  type: text("type"),
  kaatPercent: real("kaat_percent"),
  checkery: real("checkery"),
  commission: real("commission"),
  convContNo: text("conv_cont_no"),
  saleParty: text("sale_party"),
  convContNoSale: text("conv_cont_no_sale"),
  convContSale2: text("conv_cont_sale2"),
  commissionSale: real("commission_sale"),
  greyRateKp: real("grey_rate_kp"),
  kaatPercentSale: real("kaat_percent_sale"),
  checkerySale: real("checkery_sale"),
  brokerNameSale: text("broker_name_sale"),
  brokerPercentSale: real("broker_percent_sale"),
  remarks: text("remarks"),
  salAmtDiff: real("sal_amt_diff"),
  woc: real("woc"),
  wc: real("wc"),
  wck: real("wck"),
  printingName: text("printing_name"),
  commissionTotal: real("commission_total"),
  diff: real("diff"),
  termSal: text("term_sal"),
  dueDate: text("due_date"),
  typeRej: text("type_rej"),
  imgNo: text("img_no"),
  pendingFinance: text("pending_finance"),
  kpId: integer("kp_id"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_ext_pp_party").on(t.purchaseParty),
  ixDate: index("ix_ext_pp_date").on(t.vDate),
  ixKpNo: index("ix_ext_pp_kpno").on(t.kpNo),
}));

export const extPackiParchiBag = sqliteTable("ext_packi_parchi_bag", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  parchiId: integer("parchi_id").notNull().references(() => extPackiParchi.id, { onDelete: "cascade" }),
  section: text("section").notNull(),
  quality: text("quality"),
  wtPerMeter: real("wt_per_meter"),
  bags: real("bags"),
  rate: real("rate"),
  amount: real("amount"),
}, (t) => ({
  ixParchi: index("ix_ext_ppb_parchi").on(t.parchiId),
}));

export const extPackiParchiCount = sqliteTable("ext_packi_parchi_count", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  parchiId: integer("parchi_id").notNull().references(() => extPackiParchi.id, { onDelete: "cascade" }),
  code: text("code"),
  type: text("type"),
  calCount: real("cal_count"),
  ends: integer("ends"),
  ratePerLbs: real("rate_per_lbs"),
  wtPerMtr: real("wt_per_mtr"),
  costPerMtr: real("cost_per_mtr"),
  totLbs: real("tot_lbs"),
}, (t) => ({
  ixParchi: index("ix_ext_ppc_parchi").on(t.parchiId),
}));

// ============================================================
// INVENTORY (INTERNAL) — Contracts, Yarn/Beam/Grey Transactions
// Mirrors Oracle Forms 6i modules exactly. All int_* tables.
// Independent from ext_* tables (separate business records).
// ============================================================

// --- CONTRACTS ---

export const intYarnPurchaseContract = sqliteTable("int_yarn_purchase_contract", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contNo: text("cont_no").notNull().unique(),
  lContNo: integer("l_cont_no"),
  contDate: text("cont_date").notNull(),
  expdDate: text("expd_date"),
  refno: text("refno"),
  partyCode: text("party_code"),
  broker: text("broker"),
  agePercent: real("age_percent"),
  brokagePerBag: real("brokage_per_bag"),
  countCode: text("count_code"),
  ratio: text("ratio"),
  brand: text("brand"),
  qtyBags: real("qty_bags"),
  qtyLbs: real("qty_lbs"),
  ratePerLbs: real("rate_per_lbs"),
  deliveryPlace: text("delivery_place"),
  amount: real("amount"),
  days: integer("days"),
  remarks: text("remarks"),
  img: text("img"),
  status: text("status").notNull().default("R"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_int_ypc_party").on(t.partyCode),
  ixStatus: index("ix_int_ypc_status").on(t.status),
}));

export const intYarnPurchaseContractDelivery = sqliteTable("int_yarn_purchase_contract_delivery", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractId: integer("contract_id").notNull().references(() => intYarnPurchaseContract.id, { onDelete: "cascade" }),
  deliveryDate: text("delivery_date"),
  doNo: text("do_no"),
  bags: real("bags"),
  ycdDlvLoc: text("ycd_dlv_loc"),
}, (t) => ({
  ixContract: index("ix_int_ypcd_contract").on(t.contractId),
}));

export const intGreyConversionContract = sqliteTable("int_grey_conversion_contract", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contNo: text("cont_no").notNull().unique(),
  lContNo: integer("l_cont_no"),
  contDate: text("cont_date").notNull(),
  expDate: text("exp_date"),
  status: text("status").notNull().default("R"),
  type: text("type").notNull().default("CONV"),
  party: text("party"),
  weaveFrame: text("weave_frame"),
  selvType: text("selv_type"),
  slvName: text("slv_name"),
  qtyMtr: real("qty_mtr"),
  costLakhaiBorderMtr: real("cost_lakhai_border_mtr"),
  ratePerPick: real("rate_per_pick"),
  rateMtr: real("rate_mtr"),
  convRatePerMtr: real("conv_rate_per_mtr"),
  grayRatePerMtr: real("gray_rate_per_mtr"),
  loomType: text("loom_type"),
  broker: text("broker"),
  ratePick: real("rate_pick"),
  designNo: text("design_no"),
  grayQltyCode: text("gray_qlty_code"),
  img: text("img"),
  wrpWt40: real("wrp_wt_40"),
  wftWt40: real("wft_wt_40"),
  weight40: real("weight_40"),
  remarks: text("remarks"),
  read: real("read"),
  pick: real("pick"),
  width: real("width"),
  findDesign: text("find_design"),
  grayCode: text("gray_code"),
  findContract: text("find_contract"),
  warpWtPerMtr: real("warp_wt_per_mtr"),
  weftWtPerMtr: real("weft_wt_per_mtr"),
  wtPerMtr: real("wt_per_mtr"),
  warpCostPerMtr: real("warp_cost_per_mtr"),
  weftCostPerMtr: real("weft_cost_per_mtr"),
  costPerMtr: real("cost_per_mtr"),
  ratePerMtr1: real("rate_per_mtr_1"),
  ratePerMtr2: real("rate_per_mtr_2"),
  productName: text("product_name"),
  productQuality: text("product_quality"),
  seasonType: text("season_type"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_int_gcc_party").on(t.party),
  ixStatus: index("ix_int_gcc_status").on(t.status),
}));

export const intGreyConversionWarp = sqliteTable("int_grey_conversion_warp", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractId: integer("contract_id").notNull().references(() => intGreyConversionContract.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  count: text("count"),
  descr: text("descr"),
  brand: text("brand"),
  calCount: real("cal_count"),
  ends: integer("ends"),
  wtPerMtr: real("wt_per_mtr"),
  ratePerLbs: real("rate_per_lbs"),
  costPerMtr: real("cost_per_mtr"),
}, (t) => ({
  ixContract: index("ix_int_gcw_contract").on(t.contractId),
}));

export const intGreyConversionWeft = sqliteTable("int_grey_conversion_weft", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractId: integer("contract_id").notNull().references(() => intGreyConversionContract.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  count: text("count"),
  descr: text("descr"),
  brand: text("brand"),
  calCount: real("cal_count"),
  ends: integer("ends"),
  wtPerMtr: real("wt_per_mtr"),
  ratePerLbs: real("rate_per_lbs"),
  costPerMtr: real("cost_per_mtr"),
}, (t) => ({
  ixContract: index("ix_int_gcwft_contract").on(t.contractId),
}));

export const intBeamContractExtWs = sqliteTable("int_beam_contract_ext_ws", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contNo: text("cont_no").notNull().unique(),
  contDate: text("cont_date").notNull(),
  expDate: text("exp_date"),
  party: text("party"),
  sizingParty: text("sizing_party"),
  warpingParty: text("warping_party"),
  converterParty: text("converter_party"),
  wrpCode: text("wrp_code"),
  noOfWidth: real("no_of_width"),
  prdCode: text("prd_code"),
  vtype: text("vtype"),
  ends: real("ends"),
  wtPerMtr: real("wt_per_mtr"),
  ratePerBeam: real("rate_per_beam"),
  terms: text("terms"),
  remarks: text("remarks"),
  status: text("status").notNull().default("R"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_int_bcew_party").on(t.party),
  ixStatus: index("ix_int_bcew_status").on(t.status),
}));

export const intBeamContractExtWsDetail = sqliteTable("int_beam_contract_ext_ws_detail", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractId: integer("contract_id").notNull().references(() => intBeamContractExtWs.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  countCode: text("count_code"),
  brand: text("brand"),
  calCount: real("cal_count"),
  ends: real("ends"),
  wtPerMtr: real("wt_per_mtr"),
}, (t) => ({
  ixContract: index("ix_int_bcewd_contract").on(t.contractId),
}));

export const intKnottingContract = sqliteTable("int_knotting_contract", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contNo: text("cont_no").notNull().unique(),
  contDate: text("cont_date").notNull(),
  expDate: text("exp_date"),
  party: text("party"),
  type: text("type"),
  ratePerEnds: real("rate_per_ends"),
  ratePerBeam: real("rate_per_beam"),
  terms: text("terms"),
  remarks: text("remarks"),
  status: text("status").notNull().default("R"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_int_kc_party").on(t.party),
  ixStatus: index("ix_int_kc_status").on(t.status),
}));

// --- YARN RECEIPT / TRANSFER ---

export const intYarnReceipt = sqliteTable("int_yarn_receipt", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vDate: text("v_date").notNull(),
  vNo: text("v_no").notNull().unique(),
  lvNo: integer("lv_no"),
  time: text("time"),
  bookDoBiltyNo: text("book_do_bilty_no"),
  doDate: text("do_date"),
  lgpNo: text("lgp_no"),
  gpDate: text("gp_date"),
  party: text("party"),
  trnType: text("trn_type"),
  condition: text("condition").notNull().default("FRS"),
  convContNo: text("conv_cont_no"),
  purContNo: text("pur_cont_no"),
  yarnPartyTo: text("yarn_party_to"),
  timeTo: text("time_to"),
  ratePerLbsTo: real("rate_per_lbs_to"),
  amount: real("amount"),
  locationFrom: text("location_from"),
  imgBlock: text("img_block"),
  stockBag: real("stock_bag"),
  stockLbs: real("stock_lbs"),
  countCode: text("count_code"),
  warp: text("warp"),
  weft: text("weft"),
  bags: real("bags"),
  qtyLbs: real("qty_lbs"),
  ratePerLbs: real("rate_per_lbs"),
  brand: text("brand"),
  yarnLotNo: text("yarn_lot_no"),
  setNo: text("set_no"),
  ratioText: text("ratio_text"),
  remarks: text("remarks"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixParty: index("ix_int_yr_party").on(t.party),
  ixDate: index("ix_int_yr_date").on(t.vDate),
}));

export const intYarnReceiptLine = sqliteTable("int_yarn_receipt_line", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  receiptId: integer("receipt_id").notNull().references(() => intYarnReceipt.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  cartonNo: text("carton_no"),
  grossKgs: real("gross_kgs"),
  netKgs: real("net_kgs"),
  netLbs: real("net_lbs"),
}, (t) => ({
  ixReceipt: index("ix_int_yrl_receipt").on(t.receiptId),
}));

export const intYarnTransfer = sqliteTable("int_yarn_transfer", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vDate: text("v_date").notNull(),
  vNo: text("v_no").notNull().unique(),
  lvNo: integer("lv_no"),
  type: text("type"),
  condition: text("condition").notNull().default("FRS"),
  time: text("time"),
  transferFromParty: text("transfer_from_party"),
  locationFrom: text("location_from"),
  transferToParty: text("transfer_to_party"),
  locationTo: text("location_to"),
  stockBag: real("stock_bag"),
  stockLbs: real("stock_lbs"),
  countCode: text("count_code"),
  qtyBags: real("qty_bags"),
  qtyLbs: real("qty_lbs"),
  amount: real("amount"),
  ratePerLbs: real("rate_per_lbs"),
  brand: text("brand"),
  yarnLotNo: text("yarn_lot_no"),
  setNo: text("set_no"),
  imgBlock: text("img_block"),
  remarks: text("remarks"),
  rkd: real("rkd"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixDate: index("ix_int_yt_date").on(t.vDate),
  ixFrom: index("ix_int_yt_from").on(t.transferFromParty),
  ixTo: index("ix_int_yt_to").on(t.transferToParty),
}));

export const intYarnTransferLine = sqliteTable("int_yarn_transfer_line", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  transferId: integer("transfer_id").notNull().references(() => intYarnTransfer.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  cartonNo: text("carton_no"),
  grossKgs: real("gross_kgs"),
  netKgs: real("net_kgs"),
  netLbs: real("net_lbs"),
}, (t) => ({
  ixTransfer: index("ix_int_ytl_transfer").on(t.transferId),
}));

// --- EMPTY BEAM ISSUE / RETURN ---

export const intEmptyBeamIssue = sqliteTable("int_empty_beam_issue", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vDate: text("v_date").notNull(),
  vNo: text("v_no").notNull().unique(),
  lvNo: integer("lv_no"),
  trnType: text("trn_type"),
  statusType: text("status_type"),
  szgWrpParty: text("szg_wrp_party"),
  convParty: text("conv_party"),
  slipNo: text("slip_no"),
  despLoc: text("desp_loc"),
  gpNo: text("gp_no"),
  vehRegNo: text("veh_reg_no"),
  driverName: text("driver_name"),
  remarks: text("remarks"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixDate: index("ix_int_ebi_date").on(t.vDate),
  ixParty: index("ix_int_ebi_party").on(t.szgWrpParty),
}));

export const intEmptyBeamIssueLine = sqliteTable("int_empty_beam_issue_line", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  issueId: integer("issue_id").notNull().references(() => intEmptyBeamIssue.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  beamHash: text("beam_hash"),
  companyName: text("company_name"),
  emptyBWeight: real("empty_b_weight"),
}, (t) => ({
  ixIssue: index("ix_int_ebil_issue").on(t.issueId),
}));

export const intEmptyBeamReturn = sqliteTable("int_empty_beam_return", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vDate: text("v_date").notNull(),
  vNo: text("v_no").notNull().unique(),
  lvNo: integer("lv_no"),
  trnType: text("trn_type").notNull().default("SZG"),
  statusType: text("status_type").notNull().default("EXT"),
  szgWrpParty: text("szg_wrp_party"),
  convParty: text("conv_party"),
  slipNo: text("slip_no"),
  despLoc: text("desp_loc"),
  gpNo: text("gp_no"),
  vehRegNo: text("veh_reg_no"),
  driverName: text("driver_name"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixDate: index("ix_int_ebr_date").on(t.vDate),
  ixParty: index("ix_int_ebr_party").on(t.szgWrpParty),
}));

export const intEmptyBeamReturnLine = sqliteTable("int_empty_beam_return_line", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  returnId: integer("return_id").notNull().references(() => intEmptyBeamReturn.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  beamHash: text("beam_hash"),
  companyName: text("company_name"),
  emptyBWeight: real("empty_b_weight"),
}, (t) => ({
  ixReturn: index("ix_int_ebrl_return").on(t.returnId),
}));

// --- WARPED BEAM RECEIVING ---

export const intWarpedBeamReceiving = sqliteTable("int_warped_beam_receiving", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vDate: text("v_date").notNull(),
  time: text("time"),
  vNo: text("v_no").notNull().unique(),
  type: text("type").notNull().default("SZG"),
  gpNo: text("gp_no"),
  lvNo: integer("lv_no"),
  freightCharges: real("freight_charges"),
  totalAmount: real("total_amount"),
  unPostedBills: text("un_posted_bills"),
  delBill: text("del_bill"),
  billNo: text("bill_no"),
  billDate: text("bill_date"),
  billingStatus: text("billing_status"),
  beamReceivingFrom: text("beam_receiving_from"),
  beamStockLoaded: text("beam_stock_loaded"),
  remarksDestination: text("remarks_destination"),
  sizingGpNo: text("sizing_gp_no"),
  gpDate: text("gp_date"),
  resultCountSzg: text("result_count_szg"),
  bmSaleParty: text("bm_sale_party"),
  gulley: real("gulley"),
  emtBag: real("emt_bag"),
  shoper: real("shoper"),
  waste: real("waste"),
  gatta: real("gatta"),
  headConeQty: real("head_cone_qty"),
  headConeKgs: real("head_cone_kgs"),
  bagsQty: real("bags_qty"),
  bagsWeight: real("bags_weight"),
  conesQty: real("cones_qty"),
  conesWeight: real("cones_weight"),
  gulleyWeight: real("gulley_weight"),
  emtBagWeight: real("emt_bag_weight"),
  shoperWeight: real("shoper_weight"),
  wasteWeight: real("waste_weight"),
  gattaWeight: real("gatta_weight"),
  totalAmountFinal: real("total_amount_final"),
  gstFtx: real("gst_ftx"),
  netWeightRate: real("net_weight_rate"),
  amtTot: real("amt_tot"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixDate: index("ix_int_wbr_date").on(t.vDate),
  ixParty: index("ix_int_wbr_party").on(t.beamReceivingFrom),
}));

export const intWarpedBeamReceivingLine = sqliteTable("int_warped_beam_receiving_line", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  receivingId: integer("receiving_id").notNull().references(() => intWarpedBeamReceiving.id, { onDelete: "cascade" }),
  rDate: text("r_date"),
  yarnLotNo: text("yarn_lot_no"),
  yarnBrand: text("yarn_brand"),
  setNo: text("set_no"),
  beamSetNo: text("beam_set_no"),
  beamNo: text("beam_no"),
  beamStatus: text("beam_status"),
  beamLoadedHnk: real("beam_loaded_hnk"),
  emptyKg: real("empty_kg"),
  yarnBmsNetLbs: real("yarn_bms_net_lbs"),
  beamLength: real("beam_length"),
  warpingCntNo: text("warping_cnt_no"),
  wt: real("wt"),
  width: real("width"),
  ends: integer("ends"),
  rate: real("rate"),
  length: real("length"),
  conv: real("conv"),
  amount: real("amount"),
  gpNoLine: text("gp_no_line"),
}, (t) => ({
  ixReceiving: index("ix_int_wbrl_receiving").on(t.receivingId),
}));

// --- KNOTTING / SARNING BILL ---

export const intKnottingSarning = sqliteTable("int_knotting_sarning", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vDate: text("v_date").notNull(),
  party: text("party"),
  type: text("type"),
  ratePerEnds: real("rate_per_ends"),
  ratePerBeam: real("rate_per_beam"),
  vNo: text("v_no").notNull().unique(),
  lvNo: integer("lv_no"),
  warpContNoyy: text("warp_cont_noyy"),
  findDate: text("find_date"),
  unPostedBills: text("un_posted_bills"),
  delBill: text("del_bill"),
  billingStatus: text("billing_status"),
  billNo: text("bill_no"),
  billDate: text("bill_date"),
  billingAllowed: text("billing_allowed"),
  warpContnoyy: text("warp_contnoyy"),
  rem: text("rem"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixDate: index("ix_int_ks_date").on(t.vDate),
  ixParty: index("ix_int_ks_party").on(t.party),
}));

export const intKnottingSarningLine = sqliteTable("int_knotting_sarning_line", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  knottingId: integer("knotting_id").notNull().references(() => intKnottingSarning.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  beamSetNo: text("beam_set_no"),
  setNo: text("set_no"),
  noOfBeamHash: integer("no_of_beam_hash"),
  beamNo: text("beam_no"),
  beamLength: real("beam_length"),
  issueDate: text("issue_date"),
  kDate: text("k_date"),
  shdHash: text("shd_hash"),
  lmHash: text("lm_hash"),
  extShrAge: real("ext_shr_age"),
  dspType: text("dsp_type"),
  knContNo: text("kn_cont_no"),
  ends: integer("ends"),
  amount: real("amount"),
  extraCharger: real("extra_charger"),
  extAmt: real("ext_amt"),
  netAmt: real("net_amt"),
  wt: real("wt"),
  mtr: real("mtr"),
  lHash: text("l_hash"),
  kAndL: text("k_and_l"),
}, (t) => ({
  ixKnotting: index("ix_int_ksl_knotting").on(t.knottingId),
}));

// --- GREY CLOTH DESPATCH ---

export const intGreyDespatch = sqliteTable("int_grey_despatch", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vDate: text("v_date").notNull(),
  time: text("time"),
  vNo: text("v_no").notNull().unique(),
  lNo: integer("l_no"),
  doVNoFrom: text("do_v_no_from"),
  doVNoTo: text("do_v_no_to"),
  setHashAllThanPrdHashSetHash: text("set_hash_all_than_prd_hash_set_hash"),
  despatchTo: text("despatch_to"),
  despatchLocation: text("despatch_location"),
  despatchFrom: text("despatch_from"),
  convContNo: text("conv_cont_no"),
  postLotNo: text("post_lot_no"),
  shedNo: text("shed_no"),
  party: text("party"),
  doParty: text("do_party"),
  thanQty: real("than_qty"),
  convRate: real("conv_rate"),
  amnt: real("amnt"),
  gst: real("gst"),
  further: real("further"),
  gpNo: text("gp_no"),
  gpDate: text("gp_date"),
  dateFrom: text("date_from"),
  dateTo: text("date_to"),
  amtTot: real("amt_tot"),
  ftWeave: text("ft_weave"),
  designNo: text("design_no"),
  lbMtr: real("lb_mtr"),
  encCode: text("enc_code"),
  supervisor: text("supervisor"),
  vehicleNo: text("vehicle_no"),
  driver: text("driver"),
  transAdda: text("trans_adda"),
  silvagQuality: text("silvag_quality"),
  brkgPerMtr: real("brkg_per_mtr"),
  agePercent: real("age_percent"),
  comm: real("comm"),
  productBrand: text("product_brand"),
  loomType: text("loom_type"),
  blend: text("blend"),
  greyCode: text("grey_code"),
  width: real("width"),
  type: text("type").notNull().default("FRS"),
  remarks: text("remarks"),
  updateCountBlock: text("update_count_block"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixDate: index("ix_int_gd_date").on(t.vDate),
  ixParty: index("ix_int_gd_party").on(t.party),
}));

export const intGreyDespatchLine = sqliteTable("int_grey_despatch_line", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  despatchId: integer("despatch_id").notNull().references(() => intGreyDespatch.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  tSrNo: integer("t_sr_no"),
  a: real("a"),
  b: real("b"),
  c: real("c"),
  cp: real("cp"),
  rej: real("rej"),
  cpRej: real("cp_rej"),
  lengthMtrs: real("length_mtrs"),
}, (t) => ({
  ixDespatch: index("ix_int_gdl_despatch").on(t.despatchId),
}));

export const intGreyDespatchUpdateCount = sqliteTable("int_grey_despatch_update_count", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  despatchId: integer("despatch_id").notNull().references(() => intGreyDespatch.id, { onDelete: "cascade" }),
  countCode: text("count_code"),
  countDescription: text("count_description"),
  type: text("type"),
  calCount: real("cal_count"),
  ends: integer("ends"),
  ratePerLbs: real("rate_per_lbs"),
  wtPerMtr: real("wt_per_mtr"),
  costPerMtr: real("cost_per_mtr"),
  totLbs: real("tot_lbs"),
  amount: real("amount"),
  typeRej: text("type_rej"),
}, (t) => ({
  ixDespatch: index("ix_int_gduc_despatch").on(t.despatchId),
}));

export const intGreyDespatchDami = sqliteTable("int_grey_despatch_dami", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vDate: text("v_date").notNull(),
  vNo: text("v_no").notNull().unique(),
  lvNo: integer("lv_no"),
  originalDespatchId: integer("original_despatch_id").references(() => intGreyDespatch.id, { onDelete: "cascade" }),
  party: text("party"),
  doParty: text("do_party"),
  than: integer("than"),
  mtrs: real("mtrs"),
  remarks: text("remarks"),
  printedAt: text("printed_at"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixDate: index("ix_int_gdd_date").on(t.vDate),
  ixOriginal: index("ix_int_gdd_original").on(t.originalDespatchId),
}));

// --- DAILY PRODUCTION (WVG) ---

export const intDailyProduction = sqliteTable("int_daily_production", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vDate: text("v_date").notNull(),
  vNo: text("v_no").notNull().unique(),
  lvNo: integer("lv_no"),
  time: text("time"),
  shedNo: text("shed_no"),
  foldingStock: real("folding_stock"),
  designNo: text("design_no"),
  setNo: text("set_no"),
  lotNo: text("lot_no"),
  torOwn: text("tor_own"),
  grade: text("grade"),
  remarks: text("remarks"),
  prodCode: text("prod_code"),
  noOfWidths: integer("no_of_widths"),
  convContParty: text("conv_cont_party"),
  beamContParty: text("beam_cont_party"),
  szgParty: text("szg_party"),
  productQuality: text("product_quality"),
  productBrand: text("product_brand"),
  productSlvag: text("product_slvag"),
  shiftInchargeTm: text("shift_incharge_tm"),
  shiftInchargePm: text("shift_incharge_pm"),
  shiftInchargeA: text("shift_incharge_a"),
  shiftInchargeB: text("shift_incharge_b"),
  shiftInchargeC: text("shift_incharge_c"),
  postedDate: text("posted_date"),
  modifiedDate: text("modified_date"),
}, (t) => ({
  ixDate: index("ix_int_dp_date").on(t.vDate),
  ixShed: index("ix_int_dp_shed").on(t.shedNo),
}));

export const intDailyProductionSet = sqliteTable("int_daily_production_set", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  productionId: integer("production_id").notNull().references(() => intDailyProduction.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  setHash: text("set_hash"),
  mmThanSrNo: text("mm_than_sr_no"),
  aCount: real("a_count"),
  bCount: real("b_count"),
  cCount: real("c_count"),
  cpCount: real("cp_count"),
  ppcCount: real("ppc_count"),
  totalCount: real("total_count"),
  rejCount: real("rej_count"),
  beamSetNo: text("beam_set_no"),
  kSmType: text("k_s_m_type"),
  kSmDate: text("k_s_m_date"),
  beamStatus: text("beam_status"),
  dlvStatus: text("dlv_status"),
  wastWtKg: real("wast_wt_kg"),
  beamNo: text("beam_no"),
  ends: integer("ends"),
  bLength: real("b_length"),
  rcvdMtr: real("rcvd_mtr"),
  diff: real("diff"),
  shrinkage: real("shrinkage"),
}, (t) => ({
  ixProduction: index("ix_int_dps_production").on(t.productionId),
}));

export const intDailyProductionDetail = sqliteTable("int_daily_production_detail", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  productionId: integer("production_id").notNull().references(() => intDailyProduction.id, { onDelete: "cascade" }),
  srNo: integer("sr_no").notNull(),
  detailDate: text("detail_date"),
  aProd: real("a_prod"),
  bProd: real("b_prod"),
  cProd: real("c_prod"),
  totalProd: real("total_prod"),
  prodCnt: real("prod_cnt"),
  prodDiff: real("prod_diff"),
  prodAddFactor: real("prod_add_factor"),
}, (t) => ({
  ixProduction: index("ix_int_dpd_production").on(t.productionId),
}));

// --- QUICK CONTRACT (mobile capture -> accounts formalizes) ---

export const quickContracts = sqliteTable("quick_contracts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  party: text("party").notNull(),
  greyQuality: text("grey_quality"),
  quantity: real("quantity"),
  rate: real("rate"),
  notes: text("notes"),
  status: text("status").notNull().default("PENDING"),
  createdBy: text("created_by"),
  createdAt: text("created_at").notNull(),
}, (t) => ({
  ixStatus: index("ix_quick_contract_status").on(t.status),
  ixCreated: index("ix_quick_contract_created").on(t.createdAt),
}));
